[package]
name = "zk-guest-sp1-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
base58 = { workspace = true }
anyhow = { workspace = true }
