[server]
port = 3002
host = "0.0.0.0"
request_timeout_seconds = 30

[solana]
rpc_url = "http://127.0.0.1:8899"
ws_url = "wss://api.devnet.solana.com"
commitment = "confirmed"
program_id = "11111111111111111111111111111111"
# withdraw_authority is optional, so we can omit it
# withdraw_keypair_path is optional; if set, relay signs and pays fees with this keypair
# withdraw_keypair_path = "/path/to/fee-payer.json"
priority_micro_lamports = 1000
# Jito tip (0.000001 SOL minimum; increase for higher priority in congested periods)
jito_tip_lamports = 1000
max_retries = 3
retry_delay_ms = 1000

[database]
url = "postgres://postgres:postgres@localhost:5432/relay"
max_connections = 5

[redis]
url = "redis://localhost:6379"
max_connections = 10
connection_timeout_seconds = 5

[metrics]
enabled = true
port = 9090
route = "/metrics"
