# Bun configuration file
[install]
# Use exact versions
exact = false

# Registry configuration
registry = "https://registry.npmjs.org/"

[test]
# Test configuration
preload = ["./src/tests/setup.ts"]
