[package]
name = "zk-guest-sp1"
version.workspace = true
edition.workspace = true

[dependencies]
zk-guest-sp1-host = { path = "host" }

[dev-dependencies]
sp1-sdk = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
blake3 = { workspace = true }

