[workspace]
members = [
    "guest",
    "host",
]
resolver = "2"

[package]
name = "zk-guest-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-guest-sp1-host = { path = "host" }

[dev-dependencies]
sp1-sdk = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }

[workspace.dependencies]
# SP1 dependencies - matching versions from .context/sp1-solana
sp1-sdk = "5.2.1"
sp1-zkvm = "5.2.1"
sp1-build = "5.2.1"

# Common dependencies
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.143", default-features = false, features = ["alloc"] }
clap = { version = "4.5.47", features = ["derive", "env"] }
blake3 = "1.5.4"
hex = "0.4.3"
base58 = "0.2.0"
anyhow = "1.0.89"
bincode = "1.3.3"
