[package]
name = "zk-guest-sp1-host"
version.workspace = true
edition.workspace = true

[[bin]]
name = "cloak-zk"
path = "src/main.rs"

[[bin]]
name = "generate_examples"
path = "src/bin/generate_examples.rs"

[[bin]]
name = "get_vkey_hash"
path = "src/bin/get_vkey_hash.rs"

[lib]
name = "zk_guest_sp1_host"
path = "src/lib.rs"

[dependencies]
sp1-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
base58 = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
