[package]
version = "0.1.0"
name = "withdrawal-proof-program"
edition = "2021"

[dependencies]
sp1-zkvm = "5.2.1"
bincode = "1.3.3"
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
